### PR TITLE
minor tweaks and add link to repository with the errata

### PR DESCRIPTION
**Pull request by aloctavodia**

### CODE REVIEW

**Comment by aloctavodia** [comment]
hi, any comment on this?

**Comment by aloctavodia** [comment]
Hi, @suwarnarajput could you please merge this PR?

**Comment by aloctavodia** [comment]
Hi, @suwarnarajput could you please merge this PR?

**Comment by aloctavodia** [comment]
hi!

**Comment by aloctavodia** [comment]
hello!

**Review by suwarnarajput — APPROVED** [review]

**Comment by aloctavodia** [comment]
Thanks @suwarnarajput

**Comment by aloctavodia** [comment]
You close the pull request. You did not merge it. Could you please merge it.

**Pull request merged**
